### PR TITLE
Fixing compilation failure

### LINKED ISSUE #14: Typescript does not compile
I don't do a lot with Node and I've never tried to use Typescript before, so it's entirely possible that I'm just doing something wrong. However, I've tried just about everything I can think of and this project simply will not build. 

This is what I do to attempt a build:

```
npm install -g gulp
npm install
gulp
```

I then get 

```
[00:43:58] Using gulpfile ~/Projects/swiv/gulpfile.js
[00:43:58] Starting 'all'...
[00:43:58] Starting 'clean'...
[00:43:59] Finished 'clean' after 145 ms
[00:43:59] Starting 'style'...
[00:43:59] Starting 'icons'...
[00:44:00] Finished 'icons' after 1.05 s
[00:44:01] Finished 'style' after 2.31 s
[00:44:01] Starting 'server:tsc'...
[00:44:01] Starting 'client:tsc'...
node_modules/@types/express-serve-static-core/index.d.ts(242,37): error TS1110 Type expected.
node_modules/@types/express-serve-static-core/index.d.ts(243,39): error TS1110 Type expected.
```

There are dozens more Typescript errors similar to that in the log. Based on the research I've done, the `*.d.ts` files are apparently being treated as normal Typescript files in the compilation process. The type definition files are not in Typescript syntax and so they understandably throw these compilation errors.

I've done a bit with Gulp, so I tried to see if I could fix it. However, the build is using Imply's [laborer](https://github.com/implydata/laborer/tree/master) package to compile the typescript, which is completely undocumented. Seriously, even by OSS standards that project is egregious. 

Anyway, the last build in Travis appears to have worked, so I tried building this in an Ubuntu Docker container with matching major versions of the node/npm:

```
root@dfd7a351076f:/swiv# node --version
v6.11.1
root@dfd7a351076f:/swiv# npm --version
3.10.10
root@dfd7a351076f:/swiv# gulp --version
[05:01:11] CLI version 3.9.1
[05:01:11] Local version 3.9.1
```

Same problem with the latest commit (e4085f42b) and latest tag (v0.9.42):

```
root@dfd7a351076f:/swiv# ./travis-test 
[05:01:52] Using gulpfile /swiv/gulpfile.js
[05:01:52] Starting 'all'...
[05:01:52] Starting 'clean'...
[05:01:52] Finished 'clean' after 121 ms
[05:01:52] Starting 'style'...
[05:01:53] Starting 'icons'...
[05:01:54] Finished 'icons' after 1.49 s
[05:01:55] Finished 'style' after 2.76 s
[05:01:55] Starting 'server:tsc'...
[05:01:55] Starting 'client:tsc'...
/swiv/node_modules/@types/express-serve-static-core/index.d.ts(242,37): error TS1110 Type expected.
/swiv/node_modules/@types/express-serve-static-core/index.d.ts(243,39): error TS1110 Type expected.
```

Is this happening for others? I don't see any other way that I *could* build this project, but given the complete lack of documentation for laborer perhaps I'm missing something.

### PR DESCRIPTION
**Pull request by monitorjbl**
Fixes #14

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by erankor** [comment]
I just had the same problem and this patch solved it, thanks @monitorjbl!

**Comment by pjain1** [comment]
@monitorjbl Thanks for the contrib. Did you sign the CLA ? Also have you tried this in some production like setup ?

**Comment by monitorjbl** [comment]
@pjain1 I've signed the CLA and I've run the system in our environment. It does work, but in the interests of transparency I should qualify that. Swiv is a non-customer-facing ops tool for us. This version works the same as the NPM-sourced swiv installation, but I don't know if you'd consider that "production". It's certainly not run with the same rigor that we apply to other services in our environment that we do consider to be production quality. 

As I see it, this PR isn't a very big change to the build process. The build still uses laborer to compile and the codebase is almost completely unchanged save for the handful of single-line tweaks that were necessary with a non-buggy version of Typescript. The only difference is the version of laborer being incremented slightly (2.5.25 -> 2.5.27) and updating the Typescript version to a patched one (2.0.0 - > 2.0.8). Other than that, the only real change was moving laborer *into* the project instead of sourcing it from NPM.

**Comment by pjain1** [comment]
@monitorjbl Thanks for the explanation, I am also not a node expert but I think we can take it in. I have sent an invitation to you to be a Collaborator on Swiv, you can accept if you are interested.

**Comment by monitorjbl** [comment]
Sure, thanks for the invite!

**Pull request merged**
